### ISSUE TITLE
ไม่สามารถใช้งานได้

### ISSUE THREAD

**Issue by choodencio** [exzajung/class.truewallet.php#1]
ลองเขียนโค๊ดเชื่อมต่อ

require_once('class.truewallet.php');
$wallet = new TrueWallet('myemail@gmail.com','mypass','email');
echo $wallet->GetToken();

ผลลัพธ์ที่ได้ :
{"code":null,"namespace":"TMN-PRODUCT","titleTh":"ไม่สามารถทำรายการได้","titleEn":"ไม่สามารถทำรายการได้","messageTh":"กรุณารอสักครู่ แล้วทํารายการใหม่อีกครั้ง ","messageEn":"กรุณารอสักครู่ แล้วทํารายการใหม่อีกครั้ง ","originalMessage":"INTERNAL_SERVER_ERROR","developerMessage":null,"data":{}}

**Comment by exzajung** [comment]
ผมยังใช้งานได้ตามปกตินะครับ
